version: 1
formatters:
    default:
        format: '%(asctime)s - %(levelname)s - %(name)s - %(filename)s[%(lineno)d] - %(message)s'
handlers:
    console:
        class : logging.StreamHandler
        formatter: default
        level   : INFO
        stream  : ext://sys.stdout
    main_file:
        class : logging.handlers.ConcurrentRotatingFileHandler
        formatter: default
        level   : DEBUG
        filename: {base_log_dir}/main.log
        maxBytes: 1024000
        backupCount: 10
        encoding: UTF-8
    error_file:
        class : logging.handlers.ConcurrentRotatingFileHandler
        formatter: default
        level: WARNING
        filename: {base_log_dir}/error.log
        maxBytes: 1024000
        backupCount: 10
        encoding: UTF-8
loggers:
    __main__:
        level   : DEBUG
        handlers: [console, main_file, error_file]
    config_loader:
        level   : DEBUG
        handlers: [console, main_file, error_file]
    simulator:
        level   : INFO
        handlers: [console, main_file, error_file]
    azurlane:
        level   : DEBUG
        handlers: [console, main_file, error_file]
    fgo:
        level   : DEBUG
        handlers: [console, main_file, error_file]